* Story
In a land far beyond human imagination, lies a magical place called the Mushroom Kingdom. The Mushroom Kingdom is always sunny, and food is plentiful year round. The Kingdom was ruled by a gentle and peace-loving Mushroom King and his daughter, Princess Toadstool (who would later come to be known as Princess Peach.) The Mushroom people were living peacefully, and all was bliss.

Then one dark day a tribe of evil turtles named "Koopa" led by the tyrannical King Bowser invaded the tranquil Kingdom. There was a terrible war. The Mushroom people fought courageously but they were no match for the vicious turtles. They were easily defeated by the Turtle Tribe, and horrible Bowser's black magic turned all the Mushroom people into stones, bricks and even horsehair plants. Princess Toadstool, the only one with the power to free the Kingdom from the evil power of Bowser, was captured and exiled to a deep dungeon in a faraway castle.

Mario, a man of courage and determination, heard of the awful fate of the Mushroom people. He decided to save the fair Princess and free the citizens of the Mushroom Kingdom from the evil control of Bowser. This is where the legend ends, and the adventure begins. The fate of the beautiful princess and the Mushroom people is now in your hands! 
